name: Continuous Integration

# Trigger the workflow on push to the 'master' branch
on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # The environment to run this job

    steps:
      # Step 1: Checkout the source code from the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up the required version of .NET (or any other environment)
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x  # Specify your .NET version

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the application
      - name: Build project
        run: dotnet build -c Release --no-restore

      # Step 5: Run unit tests
      - name: Run tests
        run: dotnet test -c Release --no-build

      # Step 6: Publish
      - name: Publish
        run: dotnet publish -c Release -r win-x64 --output ./publish

      # ✅ Step 7: Upload Artifact (fixed)
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-publish
          path: ./publish
